import com.distinct.rpc.*;

/**
 * <b>LOGINSMPPROG Server Stub</b>
 * This class was automatically generated by Jrpcgen from the RPC/XDR file "stdin". <br>
 * LOGINSMPPROG: was interface
 */

public abstract class LOGINSMPPROGServer extends JRPCServer {

/** Program ID of the interface. */
public static final int LOGINSMPPROG = 78;

/** Version ID of the interface. */
public static final int LOGINSMPVERS = 1;

public static final int login = 1;

/**
 * Constructor that creates an RPC server which implements the "LOGINSMPPROG" interface.
 * @exception        RPCError Thrown if the call fails for any reason.
 */
public LOGINSMPPROGServer() throws RPCError {
  super(LOGINSMPPROG, LOGINSMPVERS, true);

  UnregisterServer();
  RegisterServer(StartUDP(0), false);
  RegisterServer(StartTCP(0), true);
}

/**
 * Constructor that creates an RPC server which implements the "LOGINSMPPROG" interface.
 * @param port       The port on which the server should be listening. If 0 is specified, an arbitrary default port will be chosen.
 * @exception        RPCError Thrown if the call fails for any reason.
 */
public LOGINSMPPROGServer(int port) throws RPCError {
  super(LOGINSMPPROG, LOGINSMPVERS, true);

  UnregisterServer();
  RegisterServer(StartUDP(port), false);
  RegisterServer(StartTCP(port), true);
}

/**
 * Constructor that creates an RPC server which implements the "LOGINSMPPROG" interface.
 * @param port       The port on which the server should be listening. If 0 is specified, an arbitrary default port will be chosen.
 * @param do_tcp     True to start a TCP server or false otherwise.
 * @param do_udp     True to start a UDP server or false otherwise.
 * @param do_rpcb    True to start an RPCBind server (portmapper) if one is not already running or false otherwise.
 * @exception        RPCError Thrown if the call fails for any reason.
 */
public LOGINSMPPROGServer(int port, boolean do_tcp, boolean do_udp, boolean do_rpcb) throws RPCError {
  super(LOGINSMPPROG, LOGINSMPVERS, do_rpcb);

  UnregisterServer();
  if (do_udp) RegisterServer(StartUDP(port), false);
  if (do_tcp) RegisterServer(StartTCP(port), true);
}

/**
 * Constructor that creates an RPC server which implements the "LOGINSMPPROG" interface.
 * @param port       The port on which the server should be listening. If 0 is specified, an arbitrary default port will be chosen.
 * @param prog_id    The program ID registered with the RPCBind server (portmapper).
 * @param do_tcp     True to start a TCP server or false otherwise.
 * @param do_udp     True to start a UDP server or false otherwise.
 * @param do_rpcb    True to start an RPCBind server (portmapper) if one is not already running or false otherwise.
 * @exception        RPCError Thrown if the call fails for any reason.
 */
public LOGINSMPPROGServer(int port, int prog_id, boolean do_tcp, boolean do_udp, boolean do_rpcb) throws RPCError {
  super(prog_id, LOGINSMPVERS, do_rpcb);

  UnregisterServer();
  if (do_udp) RegisterServer(StartUDP(port), false);
  if (do_tcp) RegisterServer(StartTCP(port), true);
}

/**
 * Dispatch routine which interprets the call requests sent to a server.
 * Classes which implement the actual interface must override this method.
 * @param proc       The index of the requested function.
 * @param xin        Read the input parameter from this XDR stream.
 * @param xout       Write the return parameter to this XDR stream.
 * @return           Returns true if the requested function can be served or false otherwise.
 */
public boolean DoCall(int proc, XDRStream xin, XDRStream xout) {
  try {

    switch (proc) {
      case login: {
        String arg = xin.xdr_decode_string();
        String ret = login_1(arg);
        xout.xdr_encode_string(ret);
        return true;
      }

      default:
        break;
    }

    return (proc==0)?true:false;

  }
  catch (Exception e) {
    return false;
  }
}

/**
 * Override these abstract server methods to implement the server functionality.
 */

public abstract String login_1(String arg1);
}
